---

- name: Install the webserver
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install testserver apt requirements
      apt:
        pkg:
          - python3-dev
          - python3-pip
          - default-libmysqlclient-dev
          - build-essential
        state: latest
        update_cache: true
    - name: Install flask using pip
      pip:
        name: flask-mysqldb
    - name: Copy testserver.py script
      ansible.builtin.copy:
        src: testserver.py
        dest: /opt/testserver.py
        owner: root
        group: root
        mode: u+rx,g+rx
    - name: Copy testservice.service file
      ansible.builtin.template:
        src: testserver.service
        dest: /etc/systemd/system/testserver.service
    - name: Enable systemd service
      ansible.builtin.systemd:
        name: testserver
        state: started
        enabled: yes
        daemon_reload: yes
